### ISSUE TITLE
Add cache clear button/instructions

### ISSUE THREAD

**Issue by clarkwinkelmann** [flagrow/linguist#1]
It would probably be helpful to be able to clear the cache right from the Linguist tab.

It could also include a help text on how to refresh browser cache and not forgetting Cloudflare(-like) setups.

**Comment by KazeroG** [comment]
UP ?

**Comment by clarkwinkelmann** [comment]
@KazeroG this is a low priority task given you can already do it via the command line and instructions exist on the forum, there's currently no plan to implement it. Maybe I'll add it with other features I planned for Linguist, but that's also low priority :wink:

**Comment by clarkwinkelmann** [comment]
Fixed in version 0.2 by recommending using Reflar UnCache in the README.

No need to re-invent the clear cache button in our extension.
