### ISSUE TITLE
Suggestion: Longer Field and Sorting

### ISSUE THREAD

**Issue by tjrgg** [flagrow/linguist#3]
A couple of suggestions regarding the translation keys that would improve the usability of this extension for me.

- ~~~Increase the size of the translation key field. Most of the keys are a bit long and some might not be that different from each other in the beginning.~~~ Moved to #4 
- Sort the translation keys so that they are in alphabetical order. That would help to find a key in the event something needs to be changed and you have a lot of translations.

**Comment by clarkwinkelmann** [comment]
Good ideas !

Regarding sort order, the keys are supposed to be sorted by `key` when you refresh the page. Does that not work ?

**Comment by Tyler0130** [comment]
No, it does not. It displays them in the order they are listed in the database (by `id`).

**Comment by Tyler0130** [comment]
@clarkwinkelmann What's the status on this?

**Comment by clarkwinkelmann** [comment]
@Tyler0130 Linguist isn't on our top priority list so this might have to wait a bit more :sweat_smile: 

I moved the field length to another issue. I'll take a look at the sorting issue first if I find some time :wink:

**Comment by clarkwinkelmann** [comment]
Fixed in version 0.2

The listing is now different and always sorted by key name
